// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlicxalkjcrywtlskizs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsaWN4YWxramNyeXd0bHNraXpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDkyNTUsImV4cCI6MjA2ODc4NTI1NX0.AO6W8AX5OnUP0JFa2V6iqKNcH-82SiNYVqYp2FbkN6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});
